import { Inter, Play } from "next/font/google";
import './globals.css';

export const inter = Inter({
	subsets: ['cyrillic', 'latin'],
  variable: '--font-inter',
});

export const play = Play({
	subsets: ['cyrillic', 'latin'],
  variable: '--font-play',
  weight: ['400', '700'],
});

export const metadata = {
	title: 'Monolith frame',
	description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${play.className}`}>
        {children}
      </body>
    </html>
  );
}


