import localFont from "next/font/local";
import "@/assets/global.css";
import { Inter } from "next/font/google";
import classNames from "classnames";
import myImageLoader from "@/utils/myImageLoader";

const inter = Inter({
  subsets: ["cyrillic", "latin"],
  variable: "--font-inter",
  display: "swap",
});

const halvarBreit = localFont({
  src: [
    {
      path: "./../public/fonts/Halvar Breitschrift/HalvarBreit-Md.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-halvarBreit",
  display: "swap",
});

const drucSyr = localFont({
  src: [
    {
      path: "./../public/fonts/Druc Syr/DrukCyr-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../public/fonts/Druc Syr/DrukCyr-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-DrucSyr",
  display: "swap",
});

const iconPath = myImageLoader("/icon.ico");

export const metadata = {
  title: "Monolith frame",
  description: "Generated by Next.js",
  icons: { icon: iconPath },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="ru"
      className={classNames(
        `${drucSyr.className} ${inter.variable} ${halvarBreit.variable}`,
      )}
    >
      <body className="relative">{children}</body>
    </html>
  );
}
