import { Inter, Oswald } from 'next/font/google';
import DrucSyr from 'next/font/local';
import HalvarBreit from 'next/font/local';
import './globals.css';
import Head from 'next/head';

export const inter = Inter({
  subsets: ['cyrillic', 'latin'],
  variable: '--font-inter',
});

export const halvarBreit = HalvarBreit({
	src: [
		{
			path: './../public/fonts/Halvar Breitschrift/HalvarBreit-Lt.woff2',
			weight: '300',
			style: 'normal'
		}
	]
})

export const drucSyr = DrucSyr({
  src: [
    {
      path: './../public/fonts/Druc Syr/DrukCyr-Medium.woff2',
      weight: '400',
      style: 'normal',
    },
		{
      path: './../public/fonts/Druc Syr/DrukCyr-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
	variable: '--font-DrucSyr'
});

export const metadata = {
  title: 'Monolith frame',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Head>
        <link rel='icon' href='/icon.ico' />
      </Head>
      <body className={`${drucSyr.className} ${inter.variable}`}>{children}</body>
    </html>
  );
}
